server:
  port: 8000
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ExamSys
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/examsys?serverTimezone=UTC
      username: root
      password: ycx
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*.xml

#  redis:
#    host: localhost # 本地IP 或是 虚拟机IP
#    port: 6379
#    #    password: root
#    database: 0  # 默认使用 0号db
#  cache:
#    redis:
#      time-to-live: 1800000  # 设置缓存数据的过期时间，30分钟

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，开启按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#  mapper-locations: classpath*:mapper/**/*Mapper.xml
#  type-aliases-package: com.ycx.reggie.entity
