package com.ycx.Exam.entity;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Question implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.question_type
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Integer questionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.subject_id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Long subjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.score
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.grade_level
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Integer gradeLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.difficult
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Integer difficult;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.correct
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private String correct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.info_text_content_id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Long infoTextContentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.create_user
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Long createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.status
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.create_time
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private LocalDateTime createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.deleted
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table question
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.question_type
     *
     * @return the value of question.question_type
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Integer getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.question_type
     *
     * @param questionType the value for question.question_type
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setQuestionType(Integer questionType) {
        this.questionType = questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.subject_id
     *
     * @return the value of question.subject_id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Long getSubjectId() {
        return subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.subject_id
     *
     * @param subjectId the value for question.subject_id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setSubjectId(Long subjectId) {
        this.subjectId = subjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.score
     *
     * @return the value of question.score
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.score
     *
     * @param score the value for question.score
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.grade_level
     *
     * @return the value of question.grade_level
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Integer getGradeLevel() {
        return gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.grade_level
     *
     * @param gradeLevel the value for question.grade_level
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setGradeLevel(Integer gradeLevel) {
        this.gradeLevel = gradeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.difficult
     *
     * @return the value of question.difficult
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Integer getDifficult() {
        return difficult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.difficult
     *
     * @param difficult the value for question.difficult
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setDifficult(Integer difficult) {
        this.difficult = difficult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.correct
     *
     * @return the value of question.correct
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public String getCorrect() {
        return correct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.correct
     *
     * @param correct the value for question.correct
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setCorrect(String correct) {
        this.correct = correct == null ? null : correct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.info_text_content_id
     *
     * @return the value of question.info_text_content_id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Long getInfoTextContentId() {
        return infoTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.info_text_content_id
     *
     * @param infoTextContentId the value for question.info_text_content_id
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setInfoTextContentId(Long infoTextContentId) {
        this.infoTextContentId = infoTextContentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.create_user
     *
     * @return the value of question.create_user
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.create_user
     *
     * @param createUser the value for question.create_user
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.status
     *
     * @return the value of question.status
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.status
     *
     * @param status the value for question.status
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.create_time
     *
     * @return the value of question.create_time
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public LocalDateTime getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.create_time
     *
     * @param createTime the value for question.create_time
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setCreateTime(LocalDateTime createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.deleted
     *
     * @return the value of question.deleted
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public Boolean getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.deleted
     *
     * @param deleted the value for question.deleted
     *
     * @mbggenerated Sun Feb 19 14:47:06 CST 2023
     */
    public void setDeleted(Boolean deleted) {
        this.deleted = deleted;
    }
}