package com.ycx.Exam.entity;

import java.io.Serializable;

public class TextItem implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_item.id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_item.content_id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private Long contentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_item.prefix
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private String prefix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_item.content
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table text_item
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_item.id
     *
     * @return the value of text_item.id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_item.id
     *
     * @param id the value for text_item.id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_item.content_id
     *
     * @return the value of text_item.content_id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public Long getContentId() {
        return contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_item.content_id
     *
     * @param contentId the value for text_item.content_id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public void setContentId(Long contentId) {
        this.contentId = contentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_item.prefix
     *
     * @return the value of text_item.prefix
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public String getPrefix() {
        return prefix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_item.prefix
     *
     * @param prefix the value for text_item.prefix
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public void setPrefix(String prefix) {
        this.prefix = prefix == null ? null : prefix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_item.content
     *
     * @return the value of text_item.content
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_item.content
     *
     * @param content the value for text_item.content
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}