package com.ycx.Exam.entity;

import java.io.Serializable;
import java.util.Date;

public class textContent implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_content.id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_content.title
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_content.analysis
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private String analysis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column text_content.create_time
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table text_content
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_content.id
     *
     * @return the value of text_content.id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_content.id
     *
     * @param id the value for text_content.id
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_content.title
     *
     * @return the value of text_content.title
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_content.title
     *
     * @param title the value for text_content.title
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_content.analysis
     *
     * @return the value of text_content.analysis
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public String getAnalysis() {
        return analysis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_content.analysis
     *
     * @param analysis the value for text_content.analysis
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public void setAnalysis(String analysis) {
        this.analysis = analysis == null ? null : analysis.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column text_content.create_time
     *
     * @return the value of text_content.create_time
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column text_content.create_time
     *
     * @param createTime the value for text_content.create_time
     *
     * @mbggenerated Sun Feb 19 17:26:47 CST 2023
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}